name = "TJLF"
uuid = "12ecd31c-256b-4db5-a799-cd5afeb0bd7d"
authors = ["Tom Neiser <neisert@fusion.gat.com>", "Danny Sun <dannysun@alumni.princeton.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Arpack = "0.5.3"