module TJLF

# include("tglf_isnan.o")
include("tjlf_modules.jl")
# include("tglf_pkg.o")
# include("tglf_allocate.o")
# include("tglf_deallocate.o")
# include("tglf_startup.o")
# include("tglf_hermite.o")
# include("tglf_inout.o")
# include("tglf_setup_geometry.o")
# include("tglf_LS.o")
# include("tglf_eigensolver.o")
# include("tglf_geometry.o")
# include("tglf_matrix.o")
# include("tglf_max.o")
# include("tglf_interface.o")
# include("tglf_error.o")
# include("tglf_isinf.o")
# include("tglf_shutdown.o")
# include("tglf_read_input.o")
# include("tglf_multiscale_spectrum.o")
# include("tglf_kygrid.o")
# include("tglf_run.o")
# include("tglf_TM.o")
# include("tglf_init_mpi.o")
# include("tglf_run_mpi.o")
# include("tglf_TM_mpi.o")

end