name: Make Docs
on:
  pull_request:
    branches: ["master"]
  push:
    branches:
      - master
      - docs
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/'
      - 'docs/**'
    tags: '*'
  workflow_dispatch:
    
jobs:
  make_docs:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: |
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ docs/make.jl